// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    public static partial class VertexTextureTerrainKeys
    {
        public static readonly ParameterKey<SamplerState> MeshTextureSampler = ParameterKeys.New<SamplerState>();
        public static readonly ParameterKey<Texture> Coal_ore = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Cobblestone = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Dirt = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Grass_side = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Grass_top = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Sand = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Stone = ParameterKeys.New<Texture>();
    }
}
