// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    public static partial class AtmospherePrecomputationKeys
    {
        public static readonly ParameterKey<Texture> DeltaE = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> DeltaJ = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> DeltaSR = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> DeltaSM = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<bool> IsFirst = ParameterKeys.New<bool>();
    }
}
