// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    public static partial class AtmosphereLightingKeys
    {
        public static readonly ParameterKey<float> SunIntensity = ParameterKeys.New<float>(100);
        public static readonly ParameterKey<float> Exposure = ParameterKeys.New<float>(0.4f);
        public static readonly ParameterKey<Vector3> SunDirectionVS = ParameterKeys.New<Vector3>();
        public static readonly ParameterKey<Vector3> CenterVS = ParameterKeys.New<Vector3>();
    }
}
