// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Paradox Shader Mixin Code Generator.
// To generate it yourself, please install SiliconStudio.Paradox.VisualStudio.Package .vsix
// and re-save the associated .pdxfx.
// </auto-generated>

using System;
using SiliconStudio.Core;
using SiliconStudio.Paradox.Effects;
using SiliconStudio.Paradox.Graphics;
using SiliconStudio.Paradox.Shaders;
using SiliconStudio.Core.Mathematics;
using Buffer = SiliconStudio.Paradox.Graphics.Buffer;

namespace SiliconStudio.Paradox.Effects
{
    public static partial class AtmosphereKeys
    {
        public static readonly ParameterKey<float> RayleighScaleHeight = ParameterKeys.New<float>(8.0e3f);
        public static readonly ParameterKey<float> MieScaleHeight = ParameterKeys.New<float>(1.2e3f);
        public static readonly ParameterKey<Vector3> RayleighExtinction = ParameterKeys.New<Vector3>(new Vector3(5.8e-6f,1.35e-5f,3.31e-5f));
        public static readonly ParameterKey<Vector3> MieScattering = ParameterKeys.New<Vector3>(new Vector3(4e-6f,4e-6f,4e-6f));
        public static readonly ParameterKey<Vector3> MieExtinction = ParameterKeys.New<Vector3>(new Vector3(4e-6f / 0.9f,4e-6f / 0.9f,4e-6f / 0.9f));
        public static readonly ParameterKey<float> MieAnisotropy = ParameterKeys.New<float>(0.8f);
        public static readonly ParameterKey<Texture> Transmittance = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Irradiance = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<Texture> Inscatter = ParameterKeys.New<Texture>();
        public static readonly ParameterKey<int> ViewZenithResolution = ParameterKeys.New<int>();
        public static readonly ParameterKey<int> SunZenithResolution = ParameterKeys.New<int>();
        public static readonly ParameterKey<int> ViewSunResolution = ParameterKeys.New<int>();
        public static readonly ParameterKey<int> AltitudeResolution = ParameterKeys.New<int>();
        public static readonly ParameterKey<float> GroundHeight = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> TopHeight = ParameterKeys.New<float>();
        public static readonly ParameterKey<float> HeightLimit = ParameterKeys.New<float>();
    }
}
